import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [data, setData] = useState(null);

  useEffect( async ()=> {
    const result = await axios('http://localhost:3000/api/hello');
    setData(result.data);
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <img src='http://localhost:3000/api/hello'></img>
      </main>
        
    </div>
  )
}
