import axios from 'axios'
import { set } from 'mongoose'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { faArrowRight, faArrowLeft } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

export default function Home() {

  const [images, setImages] = useState([])
  const [loaded, setLoaded] = useState(false)
  const [index, setIndex] = useState(0)

  useEffect(()=>{
    axios.get('http://localhost:3000/api/images')
      .then((response)=>{
        setImages(response.data.images)
      })
      .then(()=>{
        setLoaded(true)
      })
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {loaded ? <img src={images[index].image} className={styles.headerImage}></img> : <p></p>}
        <div>
          <button onClick={()=>{setIndex(index - 1)}} className={`${styles.imgBtn} ${styles.leftBtn}`}><FontAwesomeIcon icon={faArrowLeft} className={styles.faBtn}></FontAwesomeIcon></button>
          <button onClick={()=>{setIndex(index + 1)}} className={`${styles.imgBtn} ${styles.rightBtn}`}><FontAwesomeIcon icon={faArrowRight} className={styles.faBtn}/></button>
          <p>{index}</p>
          {loaded ? <p>{images[index].date}</p> : <p></p>}
          {loaded ? <p>{images.length}</p> : <p></p>}
        </div>
      </main>
        
    </div>
  )
}
