import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [data, setData] = useState(null);

  function getImageAtIndex(index){
    return <img src={`http://localhost:3000/api/images/${index}`} className={styles.mainImg}></img>
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {getImageAtIndex(5)}
      </main>
        
    </div>
  )
}
